// @generated by smolvm nm-based stub generation — do not edit.
//! Auto-generated stub exports for cuBLAS/cuBLASLt symbols PyTorch links but
//! that aren't yet forwarded. Each logs under SMOLVM_CUDA_SHIM_TRACE and
//! returns CUBLAS_STATUS_NOT_SUPPORTED so we can trace what torch actually calls.
#![allow(non_snake_case)]
use std::os::raw::c_int;
fn stub(name: &str) -> c_int {
    if std::env::var_os("SMOLVM_CUDA_SHIM_TRACE").is_some() {
        eprintln!("[cublas-stub] CALLED (unimplemented): {name}");
    }
    15
}
// cublasLt* are forwarded for real in lib.rs (LIB_CUBLASLT).
#[no_mangle]
pub extern "C" fn cublasCdotc_v2() -> c_int {
    stub("cublasCdotc_v2")
}
#[no_mangle]
pub extern "C" fn cublasCdotu_v2() -> c_int {
    stub("cublasCdotu_v2")
}
#[no_mangle]
pub extern "C" fn cublasCgelsBatched() -> c_int {
    stub("cublasCgelsBatched")
}
#[no_mangle]
pub extern "C" fn cublasCgemmStridedBatched() -> c_int {
    stub("cublasCgemmStridedBatched")
}
#[no_mangle]
pub extern "C" fn cublasCgemm_v2() -> c_int {
    stub("cublasCgemm_v2")
}
#[no_mangle]
pub extern "C" fn cublasCgemv_v2() -> c_int {
    stub("cublasCgemv_v2")
}
#[no_mangle]
pub extern "C" fn cublasCgeqrfBatched() -> c_int {
    stub("cublasCgeqrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasCgetrfBatched() -> c_int {
    stub("cublasCgetrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasCgetrsBatched() -> c_int {
    stub("cublasCgetrsBatched")
}
#[no_mangle]
pub extern "C" fn cublasCtrsmBatched() -> c_int {
    stub("cublasCtrsmBatched")
}
#[no_mangle]
pub extern "C" fn cublasCtrsm_v2() -> c_int {
    stub("cublasCtrsm_v2")
}
#[no_mangle]
pub extern "C" fn cublasDdot_v2() -> c_int {
    stub("cublasDdot_v2")
}
#[no_mangle]
pub extern "C" fn cublasDgelsBatched() -> c_int {
    stub("cublasDgelsBatched")
}
#[no_mangle]
pub extern "C" fn cublasDgeqrfBatched() -> c_int {
    stub("cublasDgeqrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasDgetrfBatched() -> c_int {
    stub("cublasDgetrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasDgetrsBatched() -> c_int {
    stub("cublasDgetrsBatched")
}
#[no_mangle]
pub extern "C" fn cublasDotEx() -> c_int {
    stub("cublasDotEx")
}
#[no_mangle]
pub extern "C" fn cublasDtrsmBatched() -> c_int {
    stub("cublasDtrsmBatched")
}
#[no_mangle]
pub extern "C" fn cublasGetPointerMode_v2() -> c_int {
    stub("cublasGetPointerMode_v2")
}
#[no_mangle]
pub extern "C" fn cublasSdot_v2() -> c_int {
    stub("cublasSdot_v2")
}
#[no_mangle]
pub extern "C" fn cublasSetPointerMode_v2() -> c_int {
    stub("cublasSetPointerMode_v2")
}
#[no_mangle]
pub extern "C" fn cublasSgelsBatched() -> c_int {
    stub("cublasSgelsBatched")
}
#[no_mangle]
pub extern "C" fn cublasSgemmEx() -> c_int {
    stub("cublasSgemmEx")
}
#[no_mangle]
pub extern "C" fn cublasSgeqrfBatched() -> c_int {
    stub("cublasSgeqrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasSgetrfBatched() -> c_int {
    stub("cublasSgetrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasSgetrsBatched() -> c_int {
    stub("cublasSgetrsBatched")
}
#[no_mangle]
pub extern "C" fn cublasStrsmBatched() -> c_int {
    stub("cublasStrsmBatched")
}
#[no_mangle]
pub extern "C" fn cublasZdotc_v2() -> c_int {
    stub("cublasZdotc_v2")
}
#[no_mangle]
pub extern "C" fn cublasZdotu_v2() -> c_int {
    stub("cublasZdotu_v2")
}
#[no_mangle]
pub extern "C" fn cublasZgelsBatched() -> c_int {
    stub("cublasZgelsBatched")
}
#[no_mangle]
pub extern "C" fn cublasZgemmStridedBatched() -> c_int {
    stub("cublasZgemmStridedBatched")
}
#[no_mangle]
pub extern "C" fn cublasZgemm_v2() -> c_int {
    stub("cublasZgemm_v2")
}
#[no_mangle]
pub extern "C" fn cublasZgemv_v2() -> c_int {
    stub("cublasZgemv_v2")
}
#[no_mangle]
pub extern "C" fn cublasZgeqrfBatched() -> c_int {
    stub("cublasZgeqrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasZgetrfBatched() -> c_int {
    stub("cublasZgetrfBatched")
}
#[no_mangle]
pub extern "C" fn cublasZgetrsBatched() -> c_int {
    stub("cublasZgetrsBatched")
}
#[no_mangle]
pub extern "C" fn cublasZtrsmBatched() -> c_int {
    stub("cublasZtrsmBatched")
}
#[no_mangle]
pub extern "C" fn cublasZtrsm_v2() -> c_int {
    stub("cublasZtrsm_v2")
}
#[no_mangle]
pub extern "C" fn cudnn_batch_norm4callERKNS_6TensorES4_RKSt8optionalIS2_ES8_S8_bdd() -> c_int {
    stub("cudnn_batch_norm4callERKNS_6TensorES4_RKSt8optionalIS2_ES8_S8_bdd")
}
#[no_mangle]
pub extern "C" fn cudnn_batch_norm_backward4callERKNS_6TensorES4_S4_RKSt8optionalIS2_ES8_S8_S8_dS4_(
) -> c_int {
    stub("cudnn_batch_norm_backward4callERKNS_6TensorES4_S4_RKSt8optionalIS2_ES8_S8_S8_dS4_")
}
#[no_mangle]
pub extern "C" fn cudnn_batch_norm_out4callERKNS_6TensorES4_RKSt8optionalIS2_ES8_S8_bddRS2_S9_S9_S9_(
) -> c_int {
    stub("cudnn_batch_norm_out4callERKNS_6TensorES4_RKSt8optionalIS2_ES8_S8_bddRS2_S9_S9_S9_")
}
#[no_mangle]
pub extern "C" fn cudnnConvolutionBackwardData() -> c_int {
    stub("cudnnConvolutionBackwardData")
}
#[no_mangle]
pub extern "C" fn cudnnConvolutionBackwardFilter() -> c_int {
    stub("cudnnConvolutionBackwardFilter")
}
#[no_mangle]
pub extern "C" fn cudnn_convolution_backward_stubE() -> c_int {
    stub("cudnn_convolution_backward_stubE")
}
#[no_mangle]
pub extern "C" fn cudnnConvolutionBiasActivationForward() -> c_int {
    stub("cudnnConvolutionBiasActivationForward")
}
#[no_mangle]
pub extern "C" fn cudnn_convolution_transpose_backward_stubE() -> c_int {
    stub("cudnn_convolution_transpose_backward_stubE")
}
#[no_mangle]
pub extern "C" fn cudnnCreateActivationDescriptor() -> c_int {
    stub("cudnnCreateActivationDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreateCTCLossDescriptor() -> c_int {
    stub("cudnnCreateCTCLossDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreateDropoutDescriptor() -> c_int {
    stub("cudnnCreateDropoutDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreatePoolingDescriptor() -> c_int {
    stub("cudnnCreatePoolingDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreateRNNDataDescriptor() -> c_int {
    stub("cudnnCreateRNNDataDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreateRNNDescriptor() -> c_int {
    stub("cudnnCreateRNNDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCreateSpatialTransformerDescriptor() -> c_int {
    stub("cudnnCreateSpatialTransformerDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnCTCLoss() -> c_int {
    stub("cudnnCTCLoss")
}
#[no_mangle]
pub extern "C" fn cudnnCTCLoss_v8() -> c_int {
    stub("cudnnCTCLoss_v8")
}
#[no_mangle]
pub extern "C" fn cudnnDestroyActivationDescriptor() -> c_int {
    stub("cudnnDestroyActivationDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDestroyCTCLossDescriptor() -> c_int {
    stub("cudnnDestroyCTCLossDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDestroyDropoutDescriptor() -> c_int {
    stub("cudnnDestroyDropoutDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDestroyRNNDataDescriptor() -> c_int {
    stub("cudnnDestroyRNNDataDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDestroyRNNDescriptor() -> c_int {
    stub("cudnnDestroyRNNDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDestroySpatialTransformerDescriptor() -> c_int {
    stub("cudnnDestroySpatialTransformerDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnDropoutGetStatesSize() -> c_int {
    stub("cudnnDropoutGetStatesSize")
}
#[no_mangle]
pub extern "C" fn cudnnFindConvolutionBackwardDataAlgorithmEx() -> c_int {
    stub("cudnnFindConvolutionBackwardDataAlgorithmEx")
}
#[no_mangle]
pub extern "C" fn cudnnFindConvolutionBackwardFilterAlgorithmEx() -> c_int {
    stub("cudnnFindConvolutionBackwardFilterAlgorithmEx")
}
#[no_mangle]
pub extern "C" fn cudnnFindConvolutionForwardAlgorithmEx() -> c_int {
    stub("cudnnFindConvolutionForwardAlgorithmEx")
}
#[no_mangle]
pub extern "C" fn cudnn_get_conv_benchmark_empty_cacheEv() -> c_int {
    stub("cudnn_get_conv_benchmark_empty_cacheEv")
}
#[no_mangle]
pub extern "C" fn cudnnGetConvolutionBackwardDataAlgorithm_v7() -> c_int {
    stub("cudnnGetConvolutionBackwardDataAlgorithm_v7")
}
#[no_mangle]
pub extern "C" fn cudnnGetConvolutionBackwardDataWorkspaceSize() -> c_int {
    stub("cudnnGetConvolutionBackwardDataWorkspaceSize")
}
#[no_mangle]
pub extern "C" fn cudnnGetConvolutionBackwardFilterAlgorithm_v7() -> c_int {
    stub("cudnnGetConvolutionBackwardFilterAlgorithm_v7")
}
#[no_mangle]
pub extern "C" fn cudnnGetConvolutionBackwardFilterWorkspaceSize() -> c_int {
    stub("cudnnGetConvolutionBackwardFilterWorkspaceSize")
}
#[no_mangle]
pub extern "C" fn cudnnGetConvolutionForwardAlgorithm_v7() -> c_int {
    stub("cudnnGetConvolutionForwardAlgorithm_v7")
}
#[no_mangle]
pub extern "C" fn cudnnGetCTCLossWorkspaceSize() -> c_int {
    stub("cudnnGetCTCLossWorkspaceSize")
}
#[no_mangle]
pub extern "C" fn cudnnGetCTCLossWorkspaceSize_v8() -> c_int {
    stub("cudnnGetCTCLossWorkspaceSize_v8")
}
#[no_mangle]
pub extern "C" fn cudnnGetCudartVersion() -> c_int {
    stub("cudnnGetCudartVersion")
}
#[no_mangle]
pub extern "C" fn cudnnGetFilterNdDescriptor() -> c_int {
    stub("cudnnGetFilterNdDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnGetLastErrorString() -> c_int {
    stub("cudnnGetLastErrorString")
}
#[no_mangle]
pub extern "C" fn cudnnGetRNNTempSpaceSizes() -> c_int {
    stub("cudnnGetRNNTempSpaceSizes")
}
#[no_mangle]
pub extern "C" fn cudnnGetRNNWeightParams() -> c_int {
    stub("cudnnGetRNNWeightParams")
}
#[no_mangle]
pub extern "C" fn cudnnGetRNNWeightSpaceSize() -> c_int {
    stub("cudnnGetRNNWeightSpaceSize")
}
#[no_mangle]
pub extern "C" fn cudnnGetStream() -> c_int {
    stub("cudnnGetStream")
}
#[no_mangle]
pub extern "C" fn cudnnGetTensorNdDescriptor() -> c_int {
    stub("cudnnGetTensorNdDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnGetVersion() -> c_int {
    stub("cudnnGetVersion")
}
#[no_mangle]
pub extern "C" fn cudnn_init_dropout_state4callEdblSt8optionalIN3c1010ScalarTypeEES2_INS3_6LayoutEES2_INS3_6DeviceEES2_IbE(
) -> c_int {
    stub("cudnn_init_dropout_state4callEdblSt8optionalIN3c1010ScalarTypeEES2_INS3_6LayoutEES2_INS3_6DeviceEES2_IbE")
}
#[no_mangle]
pub extern "C" fn cudnn_is_acceptableERKNS_10TensorBaseE() -> c_int {
    stub("cudnn_is_acceptableERKNS_10TensorBaseE")
}
#[no_mangle]
pub extern "C" fn cudnnPoolingForward() -> c_int {
    stub("cudnnPoolingForward")
}
#[no_mangle]
pub extern "C" fn cudnnRestoreDropoutDescriptor() -> c_int {
    stub("cudnnRestoreDropoutDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnn_rnn4callERKNS_6TensorEN3c108ArrayRefIS2_EElRKSt8optionalIS2_ES4_SB_lNS5_6SymIntESC_lbdbbNS6_ISC_EESB_(
) -> c_int {
    stub("cudnn_rnn4callERKNS_6TensorEN3c108ArrayRefIS2_EElRKSt8optionalIS2_ES4_SB_lNS5_6SymIntESC_lbdbbNS6_ISC_EESB_")
}
#[no_mangle]
pub extern "C" fn cudnnRNNBackwardData_v8() -> c_int {
    stub("cudnnRNNBackwardData_v8")
}
#[no_mangle]
pub extern "C" fn cudnnRNNBackwardWeights_v8() -> c_int {
    stub("cudnnRNNBackwardWeights_v8")
}
#[no_mangle]
pub extern "C" fn cudnnRNNForward() -> c_int {
    stub("cudnnRNNForward")
}
#[no_mangle]
pub extern "C" fn cudnnSetActivationDescriptor() -> c_int {
    stub("cudnnSetActivationDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetConvolutionGroupCount() -> c_int {
    stub("cudnnSetConvolutionGroupCount")
}
#[no_mangle]
pub extern "C" fn cudnnSetConvolutionMathType() -> c_int {
    stub("cudnnSetConvolutionMathType")
}
#[no_mangle]
pub extern "C" fn cudnnSetConvolutionNdDescriptor() -> c_int {
    stub("cudnnSetConvolutionNdDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetCTCLossDescriptorEx() -> c_int {
    stub("cudnnSetCTCLossDescriptorEx")
}
#[no_mangle]
pub extern "C" fn cudnnSetCTCLossDescriptor_v9() -> c_int {
    stub("cudnnSetCTCLossDescriptor_v9")
}
#[no_mangle]
pub extern "C" fn cudnnSetDropoutDescriptor() -> c_int {
    stub("cudnnSetDropoutDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetFilterNdDescriptor() -> c_int {
    stub("cudnnSetFilterNdDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetPooling2dDescriptor() -> c_int {
    stub("cudnnSetPooling2dDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetRNNDataDescriptor() -> c_int {
    stub("cudnnSetRNNDataDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSetRNNDescriptor_v8() -> c_int {
    stub("cudnnSetRNNDescriptor_v8")
}
#[no_mangle]
pub extern "C" fn cudnnSetSpatialTransformerNdDescriptor() -> c_int {
    stub("cudnnSetSpatialTransformerNdDescriptor")
}
#[no_mangle]
pub extern "C" fn cudnnSpatialTfGridGeneratorBackward() -> c_int {
    stub("cudnnSpatialTfGridGeneratorBackward")
}
#[no_mangle]
pub extern "C" fn cudnnSpatialTfGridGeneratorForward() -> c_int {
    stub("cudnnSpatialTfGridGeneratorForward")
}
#[no_mangle]
pub extern "C" fn cudnnSpatialTfSamplerBackward() -> c_int {
    stub("cudnnSpatialTfSamplerBackward")
}
#[no_mangle]
pub extern "C" fn cudnnSpatialTfSamplerForward() -> c_int {
    stub("cudnnSpatialTfSamplerForward")
}
#[no_mangle]
pub extern "C" fn cudnn_stubE() -> c_int {
    stub("cudnn_stubE")
}

fn rt_stub(name: &str) -> c_int {
    if std::env::var_os("SMOLVM_CUDA_SHIM_TRACE").is_some() {
        eprintln!("[cudart-stub] CALLED: {name}");
    }
    801 // cudaErrorNotSupported
}
#[no_mangle]
pub extern "C" fn cudaGraphDebugDotPrint() -> c_int {
    rt_stub("cudaGraphDebugDotPrint")
}
#[no_mangle]
pub extern "C" fn cudaIpcCloseMemHandle() -> c_int {
    rt_stub("cudaIpcCloseMemHandle")
}
#[no_mangle]
pub extern "C" fn cudaIpcGetEventHandle() -> c_int {
    rt_stub("cudaIpcGetEventHandle")
}
#[no_mangle]
pub extern "C" fn cudaIpcGetMemHandle() -> c_int {
    rt_stub("cudaIpcGetMemHandle")
}
#[no_mangle]
pub extern "C" fn cudaIpcOpenEventHandle() -> c_int {
    rt_stub("cudaIpcOpenEventHandle")
}
#[no_mangle]
pub extern "C" fn cudaIpcOpenMemHandle() -> c_int {
    rt_stub("cudaIpcOpenMemHandle")
}
#[no_mangle]
pub extern "C" fn cudaMemcpyPeerAsync() -> c_int {
    rt_stub("cudaMemcpyPeerAsync")
}
#[no_mangle]
pub extern "C" fn cudaRegisterVar() -> c_int {
    rt_stub("cudaRegisterVar")
}
/// `__cudaRegisterVar` — registers a __device__/__constant__ global. No-op:
/// forwarded workloads that don't use cudaMemcpyToSymbol never need the mapping.
#[no_mangle]
pub extern "C" fn __cudaRegisterVar(
    _fat: *mut *mut std::os::raw::c_void,
    _host_var: *mut std::os::raw::c_char,
    _dev_addr: *mut std::os::raw::c_char,
    _dev_name: *const std::os::raw::c_char,
    _ext: c_int,
    _size: usize,
    _constant: c_int,
    _global: c_int,
) {
}

// ---- remaining cudart runtime functions PyTorch links -----------------------
use std::os::raw::c_void;
#[no_mangle]
pub extern "C" fn cudaProfilerStart() -> c_int {
    0
}
#[no_mangle]
pub extern "C" fn cudaProfilerStop() -> c_int {
    0
}
#[no_mangle]
pub extern "C" fn cudaInitModule(_x: *mut c_void) -> c_int {
    0
}
#[no_mangle]
pub extern "C" fn cudaStreamGetPriority(_s: *mut c_void, priority: *mut c_int) -> c_int {
    if !priority.is_null() {
        unsafe { *priority = 0 }
    }
    0
}
#[no_mangle]
pub extern "C" fn cudaMemcpy2DAsync() -> c_int {
    rt_stub("cudaMemcpy2DAsync")
}
#[no_mangle]
pub extern "C" fn cublasCaxpy_v2() -> c_int {
    stub("cublasCaxpy_v2")
}
#[no_mangle]
pub extern "C" fn cublasCcopy_v2() -> c_int {
    stub("cublasCcopy_v2")
}
#[no_mangle]
pub extern "C" fn cublasCgemmBatched() -> c_int {
    stub("cublasCgemmBatched")
}
#[no_mangle]
pub extern "C" fn cublasCgerc_v2() -> c_int {
    stub("cublasCgerc_v2")
}
#[no_mangle]
pub extern "C" fn cublasCgeru_v2() -> c_int {
    stub("cublasCgeru_v2")
}
#[no_mangle]
pub extern "C" fn cublasChemm_v2() -> c_int {
    stub("cublasChemm_v2")
}
#[no_mangle]
pub extern "C" fn cublasChemv_v2() -> c_int {
    stub("cublasChemv_v2")
}
#[no_mangle]
pub extern "C" fn cublasCher2k_v2() -> c_int {
    stub("cublasCher2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasCher2_v2() -> c_int {
    stub("cublasCher2_v2")
}
#[no_mangle]
pub extern "C" fn cublasCherk_v2() -> c_int {
    stub("cublasCherk_v2")
}
#[no_mangle]
pub extern "C" fn cublasCher_v2() -> c_int {
    stub("cublasCher_v2")
}
#[no_mangle]
pub extern "C" fn cublasCrotg_v2() -> c_int {
    stub("cublasCrotg_v2")
}
#[no_mangle]
pub extern "C" fn cublasCrot_v2() -> c_int {
    stub("cublasCrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasCscal_v2() -> c_int {
    stub("cublasCscal_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsrot_v2() -> c_int {
    stub("cublasCsrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsscal_v2() -> c_int {
    stub("cublasCsscal_v2")
}
#[no_mangle]
pub extern "C" fn cublasCswap_v2() -> c_int {
    stub("cublasCswap_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsymm_v2() -> c_int {
    stub("cublasCsymm_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsymv_v2() -> c_int {
    stub("cublasCsymv_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsyr2k_v2() -> c_int {
    stub("cublasCsyr2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsyr2_v2() -> c_int {
    stub("cublasCsyr2_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsyrk_v2() -> c_int {
    stub("cublasCsyrk_v2")
}
#[no_mangle]
pub extern "C" fn cublasCsyr_v2() -> c_int {
    stub("cublasCsyr_v2")
}
#[no_mangle]
pub extern "C" fn cublasCtrmm_v2() -> c_int {
    stub("cublasCtrmm_v2")
}
#[no_mangle]
pub extern "C" fn cublasCtrmv_v2() -> c_int {
    stub("cublasCtrmv_v2")
}
#[no_mangle]
pub extern "C" fn cublasCtrsv_v2() -> c_int {
    stub("cublasCtrsv_v2")
}
#[no_mangle]
pub extern "C" fn cublasDasum_v2() -> c_int {
    stub("cublasDasum_v2")
}
#[no_mangle]
pub extern "C" fn cublasDgemmBatched() -> c_int {
    stub("cublasDgemmBatched")
}
#[no_mangle]
pub extern "C" fn cublasDnrm2_v2() -> c_int {
    stub("cublasDnrm2_v2")
}
#[no_mangle]
pub extern "C" fn cublasDrotg_v2() -> c_int {
    stub("cublasDrotg_v2")
}
#[no_mangle]
pub extern "C" fn cublasDrotmg_v2() -> c_int {
    stub("cublasDrotmg_v2")
}
#[no_mangle]
pub extern "C" fn cublasDrotm_v2() -> c_int {
    stub("cublasDrotm_v2")
}
#[no_mangle]
pub extern "C" fn cublasDrot_v2() -> c_int {
    stub("cublasDrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasDsymv_v2() -> c_int {
    stub("cublasDsymv_v2")
}
#[no_mangle]
pub extern "C" fn cublasDsyr2k_v2() -> c_int {
    stub("cublasDsyr2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasDsyr2_v2() -> c_int {
    stub("cublasDsyr2_v2")
}
#[no_mangle]
pub extern "C" fn cublasDsyr_v2() -> c_int {
    stub("cublasDsyr_v2")
}
#[no_mangle]
pub extern "C" fn cublasDtrmm_v2() -> c_int {
    stub("cublasDtrmm_v2")
}
#[no_mangle]
pub extern "C" fn cublasDtrmv_v2() -> c_int {
    stub("cublasDtrmv_v2")
}
#[no_mangle]
pub extern "C" fn cublasDtrsv_v2() -> c_int {
    stub("cublasDtrsv_v2")
}
#[no_mangle]
pub extern "C" fn cublasDzasum_v2() -> c_int {
    stub("cublasDzasum_v2")
}
#[no_mangle]
pub extern "C" fn cublasDznrm2_v2() -> c_int {
    stub("cublasDznrm2_v2")
}
#[no_mangle]
pub extern "C" fn cublasGetMatrixAsync() -> c_int {
    stub("cublasGetMatrixAsync")
}
#[no_mangle]
pub extern "C" fn cublasGetVectorAsync() -> c_int {
    stub("cublasGetVectorAsync")
}
#[no_mangle]
pub extern "C" fn cublasIcamax_v2() -> c_int {
    stub("cublasIcamax_v2")
}
#[no_mangle]
pub extern "C" fn cublasIcamin_v2() -> c_int {
    stub("cublasIcamin_v2")
}
#[no_mangle]
pub extern "C" fn cublasIdamax_v2() -> c_int {
    stub("cublasIdamax_v2")
}
#[no_mangle]
pub extern "C" fn cublasIdamin_v2() -> c_int {
    stub("cublasIdamin_v2")
}
#[no_mangle]
pub extern "C" fn cublasIsamax_v2() -> c_int {
    stub("cublasIsamax_v2")
}
#[no_mangle]
pub extern "C" fn cublasIsamin_v2() -> c_int {
    stub("cublasIsamin_v2")
}
#[no_mangle]
pub extern "C" fn cublasIzamax_v2() -> c_int {
    stub("cublasIzamax_v2")
}
#[no_mangle]
pub extern "C" fn cublasIzamin_v2() -> c_int {
    stub("cublasIzamin_v2")
}
#[no_mangle]
pub extern "C" fn cublasSasum_v2() -> c_int {
    stub("cublasSasum_v2")
}
#[no_mangle]
pub extern "C" fn cublasScasum_v2() -> c_int {
    stub("cublasScasum_v2")
}
#[no_mangle]
pub extern "C" fn cublasScnrm2_v2() -> c_int {
    stub("cublasScnrm2_v2")
}
#[no_mangle]
pub extern "C" fn cublasSetMatrixAsync() -> c_int {
    stub("cublasSetMatrixAsync")
}
#[no_mangle]
pub extern "C" fn cublasSetVectorAsync() -> c_int {
    stub("cublasSetVectorAsync")
}
#[no_mangle]
pub extern "C" fn cublasSgemmBatched() -> c_int {
    stub("cublasSgemmBatched")
}
#[no_mangle]
pub extern "C" fn cublasSnrm2_v2() -> c_int {
    stub("cublasSnrm2_v2")
}
#[no_mangle]
pub extern "C" fn cublasSrotg_v2() -> c_int {
    stub("cublasSrotg_v2")
}
#[no_mangle]
pub extern "C" fn cublasSrotmg_v2() -> c_int {
    stub("cublasSrotmg_v2")
}
#[no_mangle]
pub extern "C" fn cublasSrotm_v2() -> c_int {
    stub("cublasSrotm_v2")
}
#[no_mangle]
pub extern "C" fn cublasSrot_v2() -> c_int {
    stub("cublasSrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasSsymv_v2() -> c_int {
    stub("cublasSsymv_v2")
}
#[no_mangle]
pub extern "C" fn cublasSsyr2k_v2() -> c_int {
    stub("cublasSsyr2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasSsyr2_v2() -> c_int {
    stub("cublasSsyr2_v2")
}
#[no_mangle]
pub extern "C" fn cublasSsyr_v2() -> c_int {
    stub("cublasSsyr_v2")
}
#[no_mangle]
pub extern "C" fn cublasStrmm_v2() -> c_int {
    stub("cublasStrmm_v2")
}
#[no_mangle]
pub extern "C" fn cublasStrmv_v2() -> c_int {
    stub("cublasStrmv_v2")
}
#[no_mangle]
pub extern "C" fn cublasStrsv_v2() -> c_int {
    stub("cublasStrsv_v2")
}
#[no_mangle]
pub extern "C" fn cublasZaxpy_v2() -> c_int {
    stub("cublasZaxpy_v2")
}
#[no_mangle]
pub extern "C" fn cublasZcopy_v2() -> c_int {
    stub("cublasZcopy_v2")
}
#[no_mangle]
pub extern "C" fn cublasZdrot_v2() -> c_int {
    stub("cublasZdrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasZdscal_v2() -> c_int {
    stub("cublasZdscal_v2")
}
#[no_mangle]
pub extern "C" fn cublasZgemmBatched() -> c_int {
    stub("cublasZgemmBatched")
}
#[no_mangle]
pub extern "C" fn cublasZgerc_v2() -> c_int {
    stub("cublasZgerc_v2")
}
#[no_mangle]
pub extern "C" fn cublasZgeru_v2() -> c_int {
    stub("cublasZgeru_v2")
}
#[no_mangle]
pub extern "C" fn cublasZhemm_v2() -> c_int {
    stub("cublasZhemm_v2")
}
#[no_mangle]
pub extern "C" fn cublasZhemv_v2() -> c_int {
    stub("cublasZhemv_v2")
}
#[no_mangle]
pub extern "C" fn cublasZher2k_v2() -> c_int {
    stub("cublasZher2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasZher2_v2() -> c_int {
    stub("cublasZher2_v2")
}
#[no_mangle]
pub extern "C" fn cublasZherk_v2() -> c_int {
    stub("cublasZherk_v2")
}
#[no_mangle]
pub extern "C" fn cublasZher_v2() -> c_int {
    stub("cublasZher_v2")
}
#[no_mangle]
pub extern "C" fn cublasZrotg_v2() -> c_int {
    stub("cublasZrotg_v2")
}
#[no_mangle]
pub extern "C" fn cublasZrot_v2() -> c_int {
    stub("cublasZrot_v2")
}
#[no_mangle]
pub extern "C" fn cublasZscal_v2() -> c_int {
    stub("cublasZscal_v2")
}
#[no_mangle]
pub extern "C" fn cublasZswap_v2() -> c_int {
    stub("cublasZswap_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsymm_v2() -> c_int {
    stub("cublasZsymm_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsymv_v2() -> c_int {
    stub("cublasZsymv_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsyr2k_v2() -> c_int {
    stub("cublasZsyr2k_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsyr2_v2() -> c_int {
    stub("cublasZsyr2_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsyrk_v2() -> c_int {
    stub("cublasZsyrk_v2")
}
#[no_mangle]
pub extern "C" fn cublasZsyr_v2() -> c_int {
    stub("cublasZsyr_v2")
}
#[no_mangle]
pub extern "C" fn cublasZtrmm_v2() -> c_int {
    stub("cublasZtrmm_v2")
}
#[no_mangle]
pub extern "C" fn cublasZtrmv_v2() -> c_int {
    stub("cublasZtrmv_v2")
}
#[no_mangle]
pub extern "C" fn cublasZtrsv_v2() -> c_int {
    stub("cublasZtrsv_v2")
}
#[no_mangle]
pub extern "C" fn cudnnGetProperty() -> c_int {
    stub("cudnnGetProperty")
}
