// @generated by smolvm nm-based stub generation — do not edit.
//! Auto-generated: every real libcuda.so.1 driver function we don't yet
//! forward, exported as a NOT_SUPPORTED stub so the full driver ABI resolves
//! at load (PyTorch's NVIDIA math libs reference many; none of these are on
//! the basic init/compute path — those are the hand-written forwarders).
#![allow(non_snake_case)]
use std::os::raw::c_int;
#[no_mangle]
pub extern "C" fn cuArray3DCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArray3DCreate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArray3DGetDescriptor() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArray3DGetDescriptor_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayCreate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayGetDescriptor() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayGetDescriptor_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayGetMemoryRequirements() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayGetPlane() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuArrayGetSparseProperties() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessCheckpoint() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessGetRestoreThreadId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessGetState() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessLock() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessRestore() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCheckpointProcessUnlock() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpDeregisterCompleteCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpDeregisterStartCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpGetAttributeGlobal() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpRegisterCompleteCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpRegisterStartCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCoredumpSetAttributeGlobal() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxAttach() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxCreate_v3() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxCreate_v4() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxDetach() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxDisablePeerAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxEnablePeerAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxFromGreenCtx() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetApiVersion() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetCacheConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetDevice_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetDevResource() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetExecAffinity() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetLimit() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetSharedMemConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxGetStreamPriorityRange() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxPopCurrent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxPushCurrent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxRecordEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxResetPersistingL2Cache() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxSetCacheConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxSetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxSetLimit() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxSetSharedMemConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxSynchronize_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuCtxWaitEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDestroyExternalMemory() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDestroyExternalSemaphore() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceCanAccessPeer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetByPCIBusId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetDefaultMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetDevResource() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetExecAffinitySupport() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetGraphMemAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetHostAtomicCapabilities() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetLuid() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetNvSciSyncAttributes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetP2PAtomicCapabilities() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetP2PAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetPCIBusId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetProperties() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGetTexture1DLinearMaxWidth() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceGraphMemTrim() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevicePrimaryCtxReset() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevicePrimaryCtxReset_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevicePrimaryCtxSetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceRegisterAsyncNotification() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceSetGraphMemAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceSetMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceTotalMem() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDeviceUnregisterAsyncNotification() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevResourceGenerateDesc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevSmResourceSplit() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDevSmResourceSplitByCount() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuDriverGetGpuCodeIsaVersion() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLApiInit() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamConsumerAcquireFrame() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamConsumerConnect() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamConsumerConnectWithFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamConsumerDisconnect() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamConsumerReleaseFrame() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamProducerConnect() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamProducerDisconnect() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamProducerPresentFrame() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEGLStreamProducerReturnFrame() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEventDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEventElapsedTime_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEventRecord_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEventRecordWithFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuEventRecordWithFlags_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuExternalMemoryGetMappedBuffer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuExternalMemoryGetMappedMipmappedArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFlushGPUDirectRDMAWrites() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncGetModule() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncGetName() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncGetParamCount() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncGetParamInfo() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncIsLoaded() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncLoad() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncSetBlockShape() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncSetCacheConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncSetSharedMemConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuFuncSetSharedSize() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLCtxCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLCtxCreate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLGetDevices() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLGetDevices_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLInit() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObjectAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObjectAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObjectAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObject_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLMapBufferObject_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLRegisterBufferObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLSetBufferObjectMapFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLUnmapBufferObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLUnmapBufferObjectAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGLUnregisterBufferObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddBatchMemOpNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddChildGraphNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddDependencies() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddDependencies_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddEmptyNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddEventRecordNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddEventWaitNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddExternalSemaphoresSignalNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddExternalSemaphoresWaitNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddHostNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddKernelNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddKernelNode_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddMemAllocNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddMemcpyNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddMemFreeNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddMemsetNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphAddNode_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphBatchMemOpNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphBatchMemOpNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphChildGraphNodeGetGraph() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphClone() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphConditionalHandleCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphDebugDotPrint() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphDestroyNode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphEventRecordNodeGetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphEventRecordNodeSetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphEventWaitNodeGetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphEventWaitNodeSetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecBatchMemOpNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecChildGraphNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecEventRecordNodeSetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecEventWaitNodeSetEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecExternalSemaphoresSignalNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecExternalSemaphoresWaitNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecGetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecGetId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecHostNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecKernelNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecKernelNodeSetParams_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecMemcpyNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecMemsetNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecUpdate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExecUpdate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExternalSemaphoresSignalNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExternalSemaphoresSignalNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExternalSemaphoresWaitNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphExternalSemaphoresWaitNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphGetEdges() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphGetEdges_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphGetId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphGetNodes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphGetRootNodes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphHostNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphHostNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsEGLRegisterImage() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsGLRegisterBuffer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsGLRegisterImage() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsMapResources() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsMapResources_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceGetMappedEglFrame() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceGetMappedMipmappedArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceGetMappedPointer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceGetMappedPointer_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceSetMapFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsResourceSetMapFlags_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsSubResourceGetMappedArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsUnmapResources() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsUnmapResources_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsUnregisterResource() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsVDPAURegisterOutputSurface() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphicsVDPAURegisterVideoSurface() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphInstantiate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphInstantiate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphInstantiateWithFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphInstantiateWithParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphInstantiateWithParams_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeCopyAttributes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeGetParams_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphKernelNodeSetParams_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphLaunch() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphLaunch_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemAllocNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemcpyNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemcpyNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemFreeNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemsetNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphMemsetNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeFindInClone() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetContainingGraph() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetDependencies() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetDependencies_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetDependentNodes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetDependentNodes_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetEnabled() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetLocalId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetToolsId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeGetType() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeSetEnabled() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphNodeSetParams() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphReleaseUserObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphRemoveDependencies() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphRemoveDependencies_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphRetainUserObject() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphUpload() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGraphUpload_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxGetDevResource() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxGetId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxRecordEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxStreamCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuGreenCtxWaitEvent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuImportExternalMemory() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuImportExternalSemaphore() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcCloseMemHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcGetEventHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcGetMemHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcOpenEventHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcOpenMemHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuIpcOpenMemHandle_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetFunction() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetLibrary() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetName() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetParamCount() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelGetParamInfo() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuKernelSetCacheConfig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunch() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchCooperativeKernelMultiDevice() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchCooperativeKernel_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchGrid() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchGridAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchHostFunc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchHostFunc_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchHostFunc_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchHostFunc_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchKernelEx() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchKernelEx_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLaunchKernel_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryEnumerateKernels() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetGlobal() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetKernel() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetKernelCount() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetManaged() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetModule() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryGetUnifiedFunction() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryLoadData() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryLoadFromFile() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLibraryUnload() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLinkAddData() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLinkAddFile() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLinkAddFile_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLinkCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLinkDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointAddDevice() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointBindAddr() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointBindMem() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointExport() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointGetLimits() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointIdRelease() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointIdReserve() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointImport() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointQuery() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogicalEndpointUnbind() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogsCurrent() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogsDumpToFile() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogsDumpToMemory() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogsRegisterCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuLogsUnregisterCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAddressFree() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAddressReserve() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAdvise() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAdvise_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAlloc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocFromPoolAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocFromPoolAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocHost() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocHost_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocManaged() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocPitch() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemAllocPitch_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemBatchDecompressAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemBatchDecompressAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2D() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DUnaligned() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DUnaligned_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2DUnaligned_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2D_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy2D_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3D() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DBatchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DBatchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DBatchAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DBatchAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DPeer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DPeerAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DPeerAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DPeer_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3D_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3D_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DWithAttributesAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy3DWithAttributesAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoA() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoA_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoA_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoD() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoD_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoD_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoH() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoHAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoHAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoHAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoH_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyAtoH_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyBatchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyBatchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyBatchAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyBatchAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoA() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoA_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoA_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoD() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoDAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoDAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoD_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoH() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoHAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoHAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyDtoH_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoA() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoAAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoAAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoAAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoA_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoA_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoD() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoDAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoDAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyHtoD_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyPeer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyPeerAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyPeerAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyPeer_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpy_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyWithAttributesAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemcpyWithAttributesAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemDiscardAndPrefetchBatchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemDiscardAndPrefetchBatchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemDiscardBatchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemDiscardBatchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemExportToShareableHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemFree() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemFreeAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemFreeAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemFreeHost() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAddressRange() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAddressRange_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAllocationGranularity() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAllocationPropertiesFromHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetAttribute_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetDefaultMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetHandleForAddressRange() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetInfo() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemGetMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostAlloc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostGetDevicePointer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostGetDevicePointer_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostGetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostRegister() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostRegister_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemHostUnregister() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemImportFromShareableHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemMap() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemMapArrayAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemMapArrayAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolExportPointer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolExportToShareableHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolGetAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolImportFromShareableHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolImportPointer() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolSetAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPoolTrimTo() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchAsync_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchAsync_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchBatchAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemPrefetchBatchAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemRangeGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemRangeGetAttributes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemRelease() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemRetainAllocationHandle() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemSetAccess() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD16() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD16Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD16Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD16_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD16_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D16() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D16Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D16Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D16_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D16_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D32() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D32Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D32Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D32_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D32_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D8() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D8Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D8Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D8_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD2D8_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD32() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD32Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD32Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD32_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD32_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD8() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD8Async() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD8Async_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemsetD8_v2_ptds() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemSetMemPool() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMemUnmap() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMipmappedArrayCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMipmappedArrayDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMipmappedArrayGetLevel() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMipmappedArrayGetMemoryRequirements() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMipmappedArrayGetSparseProperties() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleEnumerateFunctions() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetFunctionCount() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetGlobal() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetGlobal_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetLoadingMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetSurfRef() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuModuleGetTexRef() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastAddDevice() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastBindAddr() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastBindAddr_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastBindMem() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastBindMem_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastGetGranularity() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuMulticastUnbind() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuOccupancyAvailableDynamicSMemPerBlock() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuOccupancyMaxActiveClusters() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuOccupancyMaxPotentialBlockSize() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuOccupancyMaxPotentialBlockSizeWithFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuOccupancyMaxPotentialClusterSize() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuParamSetf() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuParamSeti() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuParamSetSize() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuParamSetTexRef() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuParamSetv() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuPointerGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuPointerGetAttributes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuPointerSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuProfilerInitialize() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuProfilerStart() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuProfilerStop() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSignalExternalSemaphoresAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSignalExternalSemaphoresAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamAddCallback() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamAddCallback_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamAttachMemAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamAttachMemAsync_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBatchMemOp() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBatchMemOp_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBatchMemOp_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBatchMemOp_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCapture() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCapture_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCaptureToCig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCaptureToCig_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCaptureToGraph() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCaptureToGraph_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCapture_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginCapture_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginRecaptureToGraph() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamBeginRecaptureToGraph_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamCopyAttributes() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamCopyAttributes_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamCreateWithPriority() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamEndCapture() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamEndCapture_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamEndCaptureToCig() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamEndCaptureToCig_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetAttribute_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo_v3() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCaptureInfo_v3_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCtx() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCtx_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCtx_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetCtx_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetDevice() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetDevice_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetDevResource() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetDevResource_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetFlags_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetGreenCtx() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetId() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetId_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetPriority() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamGetPriority_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamIsCapturing() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamIsCapturing_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamQuery_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamSetAttribute() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamSetAttribute_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamSynchronize_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamUpdateCaptureDependencies() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamUpdateCaptureDependencies_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamUpdateCaptureDependencies_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamUpdateCaptureDependencies_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitEvent_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue32() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue32_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue32_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue32_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue64() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue64_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue64_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWaitValue64_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue32() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue32_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue32_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue32_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue64() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue64_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue64_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuStreamWriteValue64_v2_ptsz() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSubgridCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSubgridWorkerGridCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSubgridWorksetCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSurfObjectCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSurfObjectDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSurfObjectGetResourceDesc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSurfRefGetArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuSurfRefSetArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTensorMapEncodeIm2col() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTensorMapEncodeIm2colWide() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTensorMapReplaceAddress() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexObjectCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexObjectDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexObjectGetResourceDesc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexObjectGetResourceViewDesc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexObjectGetTextureDesc() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefDestroy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetAddress() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetAddressMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetAddress_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetBorderColor() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetFilterMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetFormat() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetMaxAnisotropy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetMipmapFilterMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetMipmapLevelBias() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetMipmapLevelClamp() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefGetMipmappedArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddress() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddress2D() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddress2D_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddress2D_v3() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddressMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetAddress_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetBorderColor() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetFilterMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetFlags() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetFormat() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetMaxAnisotropy() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetMipmapFilterMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetMipmapLevelBias() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetMipmapLevelClamp() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuTexRefSetMipmappedArray() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuThreadExchangeStreamCaptureMode() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuUserObjectCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuUserObjectRelease() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuUserObjectRetain() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuVDPAUCtxCreate() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuVDPAUCtxCreate_v2() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuVDPAUGetDevice() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuWaitExternalSemaphoresAsync() -> c_int {
    801
}
#[no_mangle]
pub extern "C" fn cuWaitExternalSemaphoresAsync_ptsz() -> c_int {
    801
}
